%YAML 1.1
---
language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - pypy
install:
  - pip install -e .
  - pip install -r test-requirements.txt
  - pip install tornado
script: nosetests
after_success:
  - coveralls
# deploy:
#   provider: pypi
#   user: sprockets
#   distributions: "sdist bdist_wheel"
#   on:
#     python: 2.7
#     tags: true
#     all_branches: true
#   password:
#     secure: bBvJ6OIyeEb6dw7OiNiXXZwCiY6B9AqczH7uA0bTlQArF3glJxTBz7xRVaXQZpL36IWW591VFmu8YIrHiNY1eIUhIAP74BRSQyHxyvfU7HMr5R9qQrBaoBJOU
